### ISSUE TITLE
BATTLE OF RUNTEQ Vol2レビュー

### ISSUE THREAD

**Issue by hisaju** [gittaiki/saunaiko#96]
LINE::Botの処理をラップするクラスを作っていたりコード的にはきれいだと思ったので、ほぼ指摘するところはなかったのですが笑、細かいところだけ記載しますね。
あと、機能的にもう少しサーバサイドのコードを厚くしたほうが就活的にもよさそうなので、追加機能として何か追加出来ないかご検討ください。

------
https://github.com/gittaiki/saunaiko/blob/698c1abf785f3ac65746065fa7153383c5375f38/app/models/user.rb#L11

watched? と過去形にしたほうが意味が伝わりやすそうですね。

https://github.com/gittaiki/saunaiko/blob/698c1abf785f3ac65746065fa7153383c5375f38/app/controllers/application_controller.rb#L22

これわざわざpaginate_arrayを使ってる理由はなんでしょう？？

**Comment by gittaiki** [comment]
b1dcd2d0d36af564fb3b7143c4650941465d5295
LINEで位置情報を送信すると、送信された位置付近のサウナがわかる機能を追加しました。
機能追加のため、Google Places apiを利用しています。
